### PR TITLE
Changes requested to README

### PR DESCRIPTION
**Pull request by TheDHCreator**
I fixed everything with those commits that were accidentally lumped into my previous PR, and those changes you requested for the README that be kept are in the commit below. Let me know if you want any changes made before it is merged. Thank you so much!

### CODE REVIEW

**Comment by TheDHCreator** [comment]
It looks like all the checks have passed, @acomodi. Let me know if you want any changes before you merge. Thanks!

**Comment by tmichalak** [comment]
@TheDHCreator looks good, just maybe leave out the python version in the example - `python3.7 -> python3` should be fine.

**Comment by TheDHCreator** [comment]
@tmichalak Okay, I will make that change and push it right away.

**Comment by TheDHCreator** [comment]
That change has been made and pushed. Let me know @tmichalak if you would like any more changes before merging. Thanks again!

**Comment by tmichalak** [comment]
Thanks @TheDHCreator, LGTM. Merging.

**Pull request merged**
